FROM public.ecr.aws/lambda/python:3.9
RUN yum install -y zip
WORKDIR /lambda

ADD src/ /lambda/
RUN pip install --quiet -t /lambda -r /lambda/aws_cloudformation_power_switch.egg-info/requires.txt
RUN find /lambda -type d | xargs -n 1 -I {} chmod ugo+rx "{}" && \
    find /lambda -type f | xargs -n 1 -I {} chmod ugo+r "{}"

RUN python -m compileall -q /lambda

ARG ZIPFILE=lambda.zip
RUN zip --quiet -9r /${ZIPFILE}  .

FROM scratch
ARG ZIPFILE
COPY --from=0 /${ZIPFILE} /
